apps/frontend/lib/frontend_web/router.ex
defmodule FrontendWeb.Router do
  use FrontendWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", FrontendWeb do
    pipe_through :browser

    get "/", GameController, :index
    post "/new", GameController, :new_game
    post "/join", GameController, :join_game
    get "/game", GameController, :game
  end

  # Other scopes may use custom stacks.
  # scope "/api", FrontendWeb do
  #   pipe_through :api
  # end
end

apps/frontend/lib/frontend/game_form.ex
defmodule Frontend.GameForm do
  use Ecto.Schema
  import Ecto.Changeset
  alias Frontend.GameForm

  embedded_schema do
    field(:player_coins, :integer)
    field(:player_name, :string)
    field(:small_blind, :integer)
  end

  def changeset(game_form, attrs \\ %{}) do
    cast(game_form, attrs, [:player_name, :small_blind, :player_coins])
  end

  def new_game(%GameForm{} = game_form, attrs) do
    game_form
    |> changeset(attrs)
    |> cast(attrs, [:player_name, :small_blind, :player_coins])
    |> validate_required([:player_name, :small_blind, :player_coins])
    |> validate_length(:player_name, max: 50)
    |> validate_number(:small_blind, greater_than_or_equal_to: 5, less_than: 10000)
    |> validate_number(:player_coins, greater_than_or_equal_to: 20, less_than: 10000)
    |> validate_blind_and_coins(:small_blind, :player_coins)
    |> apply_action(:insert)
  end

  def validate_blind_and_coins(changeset, small_blind, player_coins) do
    {_, sb_value} = fetch_field(changeset, small_blind)
    {_, pc_value} = fetch_field(changeset, player_coins)

    if sb_value * 4 > pc_value do
      add_error(changeset, player_coins, "coins must be at least 4x the small blind")
    else
      changeset
    end
  end
end

apps/frontend/lib/frontend_web/controllers/game_controller.ex
defmodule FrontendWeb.GameController do
  use FrontendWeb, :controller
  alias Phoenix.LiveView.Controller
  import Phoenix.PubSub
  alias Frontend.GameForm

  def index(conn, _params) do
    changeset = GameForm.changeset(%GameForm{}, %{})
    render(conn, "index.html", changeset: changeset)
  end

  def new_game(conn, %{"game_form" => game_params}) do
    case GameForm.new_game(%GameForm{}, game_params) do
      {:ok, game_form} ->
        game =
          {:via, _, {_, game_name}} =
          Engine.new_game(
            small_blind: game_form.small_blind,
            player_coins: game_form.player_coins
          )

        {:ok, log_server} = Engine.LogServer.start_link()

        :ok = Engine.add_logger(game, log_server)
        {:ok, player_id} = Engine.add_player(game, game_form.player_name)

        conn
        |> put_session(:game_name, game_name)
        |> put_session(:player_id, player_id)
        |> redirect(to: "/game")

      {:error, changeset} ->
        render(conn, "index.html", changeset: changeset)
    end
  end

  def join_game(conn, %{"game_name" => game_name, "player_name" => player_name}) do
    game = Engine.via_tuple(game_name)
    {:ok, player_id} = Engine.add_player(game, player_name)

    FrontendWeb.GameLive.process_action_queue(game_name)

    conn
    |> put_session(:game_name, game_name)
    |> put_session(:player_id, player_id)
    |> redirect(to: "/game")
  end

  def game(conn, _) do
    case get_session(conn) do
      %{"game_name" => _, "player_id" => _} = session -> render_game(conn, session)
      _ -> send_resp(conn, :not_found, "Game not found")
    end
  end

  defp render_game(conn, %{"game_name" => game_name, "player_id" => player_id}) do
    game = Engine.via_tuple(game_name)

    Controller.live_render(conn, FrontendWeb.GameLive,
      session: %{
        game_name: game_name,
        error: nil,
        player_id: player_id,
        game: Engine.status(game)
      }
    )
  end
end

apps/frontend/lib/frontend_web/live/game_live.ex
defmodule FrontendWeb.GameLive do
  use Phoenix.LiveView
  import Phoenix.PubSub

  alias Phoenix.LiveView.Socket

  def render(assigns) do
    FrontendWeb.GameView.render("game.html", assigns)
  end

  def mount(%{game_name: game_name} = assigns, socket) do
    if connected?(socket) do
      :ok = subscribe(FrontendWeb.PubSub, "game/#{game_name}")
    else
      :ok = unsubscribe(FrontendWeb.PubSub, "game/#{game_name}")
    end

    {:ok, assign(socket, assigns)}
  end

  def process_action_queue(game_name) do
    game =
      game_name
      |> Engine.via_tuple()
      |> Engine.status()

    actions =
      game.log_server
      |> Engine.LogServer.process_queue()
      |> Enum.reverse()

    Task.start(fn ->
      Enum.each(actions, fn {action, game, opts} ->
        if Keyword.get(opts, :broadcast) do
          update_clients(game_name, game)
          if delay = Keyword.get(opts, :delay), do: :timer.sleep(delay)
        end
      end)
    end)
  end

  def update_clients_and_reply(socket) do
    process_action_queue(socket.assigns.game_name)
    {:noreply, socket}
  end

  def update_clients(game_name, game) do
    broadcast(
      FrontendWeb.PubSub,
      "game/#{game_name}",
      {:game_state_updated, game}
    )
  end

  def handle_info({:game_state_updated, game}, socket) do
    {:noreply, assign(socket, :game, game)}
  end

  def handle_event("start_game", _, socket) do
    game = Engine.via_tuple(socket.assigns.game_name)

    case Engine.start_game(game) do
      :ok -> update_clients_and_reply(socket)
      error -> handle_error(error, socket)
    end
  end

  def handle_event("check", _, socket) do
    game = Engine.via_tuple(socket.assigns.game_name)
    player_id = socket.assigns.player_id

    case Engine.check(game, player_id) do
      :ok -> update_clients_and_reply(socket)
      error -> handle_error(error, socket)
    end
  end

  def handle_event("bet", %{"amount" => amount}, socket) do
    game = Engine.via_tuple(socket.assigns.game_name)
    player_id = socket.assigns.player_id
    amount = String.to_integer(amount)

    case Engine.bet(game, player_id, amount) do
      :ok -> update_clients_and_reply(socket)
      error -> handle_error(error, socket)
    end
  end

  def handle_event("call_bet", _, socket) do
    game = Engine.via_tuple(socket.assigns.game_name)
    player_id = socket.assigns.player_id

    case Engine.call_bet(game, player_id) do
      :ok -> update_clients_and_reply(socket)
      error -> handle_error(error, socket)
    end
  end

  def handle_event("fold", _, socket) do
    game = Engine.via_tuple(socket.assigns.game_name)
    player_id = socket.assigns.player_id

    case Engine.fold(game, player_id) do
      :ok -> update_clients_and_reply(socket)
      error -> handle_error(error, socket)
    end
  end

  def handle_event(_, _, socket), do: {:noreply, socket}

  defp handle_error({:error, err}, socket) do
    IO.inspect(err)
    {:noreply, assign(socket, :error, Atom.to_string(err))}
  end

  defp handle_error(:error, socket), do: {:noreply, assign(socket, :error, "unknown error")}
end

apps/frontend/lib/frontend_web/views/game_view.ex
defmodule FrontendWeb.GameView do
  use FrontendWeb, :view

  def game_admin?(game, player_id) do
    player_id == game.players |> Map.keys() |> Enum.sort() |> List.first()
  end

  def current_player?(game, player_id) do
    game.player_turn == player_id
  end

  def get_current_player(game) do
    game.players[game.player_turn]
  end

  def cards_to_repr(cards) do
    cards |> Enum.map(&Engine.Card.to_repr/1) |> Enum.join(" ")
  end

  def log(game) do
    game.log
    |> Enum.join("\n")
  end

  def minimum_bet(game) do
    case game.bet do
      0 -> game.big_blind
      x -> x + 1
    end
  end
end

apps/frontend/lib/frontend_web/templates/game/game.html.leex
<div class="bg-gray-300 py-2">
  <ul class="flex container mx-auto">
    <li class="mr-4">Game: <b><%= @game_name %></b></li>
    <li class="mr-4">Phase: <b><%= Atom.to_string(@game.phase) %></b></li>
  </ul>
</div>

<div class="container mx-auto px-4">
  <%= if @game.phase == :initializing do %>
    <div class="box">
      <h2>Current players</h2>
      <ul>
        <%= for {_, player} <- @game.players do %>
          <li><%= player.name %></li>
        <% end %>
      </ul>
      <%= if map_size(@game.players) > 1 && game_admin?(@game, @player_id) do %>
        <button phx-click="start_game">Start Game</button>
      <% end %>
    </div>
  <% else %>

    <div class="text-center text-3xl py-12">
      <p>Pot: <%= @game.pot %></p>
      <%= if @game.bet > 0 do %><p class="text-xl">Bet to match: <%= @game.bet %></p><% end %>
      <%= if length(@game.board) > 0 do %>
        <%= cards_to_repr(@game.board) %>
      <% end %>
    </div>


    <div class="flex flex-row text-center">
    <%= for {i, player} <- @game.players do %>
      <div class="flex-1 mx-2 px-4 py-4 rounded-full <%= if i == @game.player_turn, do: "bg-gray-300" %>">
        <b class="text-lg font-bold">
          <%= player.name %>
          <%= if @game.dealer == i do %><span class="ml-1 rounded-full text-sm text-black px-2 py-1 bg-yellow-400 font-bold">D</span><% end %>
          <%= if @player_id == i do %><span class="ml-1 rounded-full text-sm text-white px-2 py-1 bg-gray-600 font-bold">You</span><% end %>
        </b>
        <p>
          <%= player.coins %>
          <%= if player.bet > 0, do: " (#{player.bet} in pot)" %>
        </p>
        <%= if i == @player_id do %>
        <div class="text-xl">
          <%= cards_to_repr(player.hand) %>
        </div>
        <% end %>
        <%= if player.action do %>
          <p>
            <span class="rounded-full px-3 py-1 text-sm font-semibold bg-gray-500"><%= Atom.to_string(player.action) %></span>
          </p>
        <% end %>
      </div>
    <% end %>
    </div>
  <% end %>
  </div>

  <div class="container mx-auto mt-4">


  <%= if @game.phase != :initializing && current_player?(@game, @player_id) do %>
    Your turn:

    <%= if get_current_player(@game).bet == @game.bet do %>
      <button phx-click="check" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Check</button>
    <% else %>
      <button phx-click="call_bet" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Call <%= @game.bet - get_current_player(@game).bet %></button>
    <% end %>

    <%= if get_current_player(@game).coins > (@game.bet - get_current_player(@game).bet) do %>
      <form phx-submit="bet" class="inline">
        <input type="number" name="amount" class="bg-gray-300 py-2 px-4 rounded w-auto" min="<%= minimum_bet(@game) %>" max="<%= get_current_player(@game).coins + get_current_player(@game).bet %>" value="<%= minimum_bet(@game) %>">
        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
          <%= if @game.bet > 0, do: "Raise", else: "Bet" %>
        </button>
      </form>
    <% end %>

    <button phx-click="fold" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Fold</button>

  <% end %>

</div>

<div class="py-8"></div>

<pre>
  <%= log(@game) %>
</pre>

<code>
  <%= inspect(@game) %>

</code>

apps/frontend/lib/frontend_web/templates/game/index.html.eex
<div class="container mx-auto">
<h1 class="text-4xl my-6">Ye Olde Poker</h1>

<%= f = form_for @changeset, Routes.game_path(@conn, :new_game), method: :post, class: "my-5" %>
<p class="my-2"><%= text_input f, :player_name, class: "bg-gray-300 py-2 px-4 rounded", placeholder: "your name" %> <%= error_tag f, :player_name %></p>
<p class="my-2"><%= number_input f, :small_blind, class: "bg-gray-300 py-2 px-4 rounded", placeholder: "the small blind" %> <%= error_tag f, :small_blind %></p>
<p class="my-2"><%= number_input f, :player_coins, class: "bg-gray-300 py-2 px-4 rounded", placeholder: "coins per player" %> <%= error_tag f, :player_coins %></p>
<p class="my-2"><%= submit "New Game", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %></p>
</form>

— or —

<%= f = form_for @conn, Routes.game_path(@conn, :join_game), method: :post, class: "my-5" %>
<p class="my-2"><%= text_input f, :game_name, class: "bg-gray-300 py-2 px-4 rounded", placeholder: "game name" %></p>
<p class="my-2"><%= text_input f, :player_name, class: "bg-gray-300 py-2 px-4 rounded", placeholder: "your name" %></p>
<p class="my-2"><%= submit "Join", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %></p>
</form>
</div>